"""empty message

Revision ID: 5349214b0828
Revises: 8fcbd92ffb9b
Create Date: 2021-07-22 05:39:06.398186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5349214b0828'
down_revision = '8fcbd92ffb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('messageid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('destinationuserid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinationuserid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.create_index(op.f('ix_messages_destinationuserid'), 'messages', ['destinationuserid'], unique=False)
    op.drop_column('offers', 'read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_destinationuserid'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
