"""empty message

Revision ID: 6c16931c3979
Revises: 
Create Date: 2021-07-06 07:09:38.485823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c16931c3979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('googleId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('profilePic', sa.String(length=100), nullable=True),
    sa.Column('cky', sa.Boolean(), nullable=True),
    sa.Column('cash', sa.Boolean(), nullable=True),
    sa.Column('octopus', sa.Boolean(), nullable=True),
    sa.Column('payme', sa.Boolean(), nullable=True),
    sa.Column('tapngo', sa.Boolean(), nullable=True),
    sa.Column('bankTransfer', sa.Boolean(), nullable=True),
    sa.Column('wechatPay', sa.Boolean(), nullable=True),
    sa.Column('alipay', sa.Boolean(), nullable=True),
    sa.Column('eCheque', sa.Boolean(), nullable=True),
    sa.Column('buyer', sa.Boolean(), nullable=True),
    sa.Column('seller', sa.Boolean(), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=True),
    sa.Column('inSchoolExchange', sa.Boolean(), nullable=True),
    sa.Column('meetup', sa.Boolean(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.Column('signal', sa.Boolean(), nullable=True),
    sa.Column('telegram', sa.Boolean(), nullable=True),
    sa.Column('customContactInfo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('googleId')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('listings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ownerid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bookid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('quality', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Boolean(), nullable=True),
    sa.Column('customInfo', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bookid'], ['books.id'], ),
    sa.ForeignKeyConstraint(['ownerid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
