"""empty message

Revision ID: 8fcbd92ffb9b
Revises: 
Create Date: 2021-07-13 01:27:13.666700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fcbd92ffb9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('googleId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('profilePic', sa.String(length=100), nullable=True),
    sa.Column('cky', sa.Boolean(), nullable=True),
    sa.Column('cash', sa.Boolean(), nullable=True),
    sa.Column('octopus', sa.Boolean(), nullable=True),
    sa.Column('payme', sa.Boolean(), nullable=True),
    sa.Column('tapngo', sa.Boolean(), nullable=True),
    sa.Column('bankTransfer', sa.Boolean(), nullable=True),
    sa.Column('wechatPay', sa.Boolean(), nullable=True),
    sa.Column('alipay', sa.Boolean(), nullable=True),
    sa.Column('eCheque', sa.Boolean(), nullable=True),
    sa.Column('buyer', sa.Boolean(), nullable=True),
    sa.Column('seller', sa.Boolean(), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=True),
    sa.Column('inSchoolExchange', sa.Boolean(), nullable=True),
    sa.Column('meetup', sa.Boolean(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.Column('signal', sa.Boolean(), nullable=True),
    sa.Column('telegram', sa.Boolean(), nullable=True),
    sa.Column('customContactInfo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('googleId')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.create_table('listings',
    sa.Column('listingid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ownerid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bookid', sa.String(), nullable=True),
    sa.Column('price', sa.SmallInteger(), nullable=True),
    sa.Column('condition', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.SmallInteger(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ownerid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('listingid')
    )
    op.create_index(op.f('ix_listings_bookid'), 'listings', ['bookid'], unique=False)
    op.create_index(op.f('ix_listings_listingid'), 'listings', ['listingid'], unique=False)
    op.create_index(op.f('ix_listings_ownerid'), 'listings', ['ownerid'], unique=False)
    op.create_table('offers',
    sa.Column('offerid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('listingid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('buyerid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sellerid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['buyerid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['listingid'], ['listings.listingid'], ),
    sa.ForeignKeyConstraint(['sellerid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('offerid')
    )
    op.create_index(op.f('ix_offers_buyerid'), 'offers', ['buyerid'], unique=False)
    op.create_index(op.f('ix_offers_listingid'), 'offers', ['listingid'], unique=False)
    op.create_index(op.f('ix_offers_offerid'), 'offers', ['offerid'], unique=False)
    op.create_index(op.f('ix_offers_sellerid'), 'offers', ['sellerid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_sellerid'), table_name='offers')
    op.drop_index(op.f('ix_offers_offerid'), table_name='offers')
    op.drop_index(op.f('ix_offers_listingid'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyerid'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_listings_ownerid'), table_name='listings')
    op.drop_index(op.f('ix_listings_listingid'), table_name='listings')
    op.drop_index(op.f('ix_listings_bookid'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
